// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PLANCAR_DAO.Data;

#nullable disable

namespace PLANCARDAO.Migrations
{
    [DbContext(typeof(PlancarDbContext))]
    [Migration("20241201211912_ChangeTableNameToSingular")]
    partial class ChangeTableNameToSingular
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PLANCAR_DAO.Models.Constat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEffectue")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("DemandeUtilisationId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("DommageId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("EffectuePar")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LocalisationPhotos")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TypeConstat")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeUtilisationId");

                    b.HasIndex("DommageId");

                    b.ToTable("Constat");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.DemandeUtilisation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DebutUtilisation")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DescriptionDestination")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("DestinationId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("FinUtilisation")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NoDemande")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("StatutDemande")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long>("VehiculeId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("DemandeUtilisation");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.Departement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Departement");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.Dommage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Dommage");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.Institution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Adresse")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EmailResponsable")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("LocalisationId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NomResponsable")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Telephone")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TelephoneResponsable")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("LocalisationId");

                    b.ToTable("Institution");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.Utilisateur", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Privilege")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("StatutCompte")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.Vehicule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DateService")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsAssuranceEnRegle")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsVehiculeVole")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("StatutVehicule")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Vehicule");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.Ville", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DepartementId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId");

                    b.ToTable("Ville");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.Constat", b =>
                {
                    b.HasOne("PLANCAR_DAO.Models.DemandeUtilisation", "DemandeUtilisation")
                        .WithMany()
                        .HasForeignKey("DemandeUtilisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PLANCAR_DAO.Models.Dommage", "Dommage")
                        .WithMany()
                        .HasForeignKey("DommageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeUtilisation");

                    b.Navigation("Dommage");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.DemandeUtilisation", b =>
                {
                    b.HasOne("PLANCAR_DAO.Models.Ville", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PLANCAR_DAO.Models.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PLANCAR_DAO.Models.Vehicule", "Vehicule")
                        .WithMany()
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Institution");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.Institution", b =>
                {
                    b.HasOne("PLANCAR_DAO.Models.Ville", "Localisation")
                        .WithMany()
                        .HasForeignKey("LocalisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localisation");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.Utilisateur", b =>
                {
                    b.HasOne("PLANCAR_DAO.Models.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("PLANCAR_DAO.Models.Ville", b =>
                {
                    b.HasOne("PLANCAR_DAO.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");
                });
#pragma warning restore 612, 618
        }
    }
}
